"use client";

import { useEffect, useMemo, useState } from "react";
import { createFinancialTransaction, deleteFinancialTransaction, listFinanceAccounts, listFinanceCategories, listFinancialTransactions, updateFinancialTransaction, type FinancialTransaction, type FinanceAccount } from "@/lib/api/financeClient";
import { FinanceShell, vnd, typeClass, typeLabel } from "@/components/finance/FinanceShell";
import type { FinanceCategoryDto, UpdateFinancialTransactionInput } from "@card-credit/contracts";

const today = () => new Date().toISOString().slice(0, 10);
const editableTypes = ["EXPENSE", "INCOME", "REIMBURSEMENT", "REFUND", "CASHBACK"] as const;
const typeNames: Record<string, string> = { EXPENSE: "Chi tiêu", INCOME: "Thu nhập", REIMBURSEMENT: "Hoàn tiền chi hộ", REFUND: "Hoàn tiền", CASHBACK: "Cashback" };
type FormState = { accountId: string; transactionDate: string; amount: number | ""; categoryId: string; transactionType: typeof editableTypes[number]; ownership: "PERSONAL" | "PAID_FOR_OTHER"; serviceFeeRate: number | ""; reimbursementExpected: number | ""; refundReceived: number | ""; cashbackReceived: number | ""; note: string };
const blankForm = (accountId = ""): FormState => ({ accountId, transactionDate: today(), amount: "", categoryId: "OTHER", transactionType: "EXPENSE", ownership: "PERSONAL", serviceFeeRate: "", reimbursementExpected: "", refundReceived: "", cashbackReceived: "", note: "" });
const toForm = (row: FinancialTransaction): FormState => ({ accountId: row.accountId, transactionDate: row.transactionDate, amount: row.amount, categoryId: row.categoryId, transactionType: (editableTypes.includes(row.transactionType as typeof editableTypes[number]) ? row.transactionType : "EXPENSE") as FormState["transactionType"], ownership: row.ownership, serviceFeeRate: row.serviceFeeRate ?? "", reimbursementExpected: row.impact.outstandingReceivable, refundReceived: row.impact.reimbursementReceived, cashbackReceived: 0, note: row.note });

export default function TransactionsPage() {
  const [rows, setRows] = useState<FinancialTransaction[]>([]); const [accounts, setAccounts] = useState<FinanceAccount[]>([]); const [categories, setCategories] = useState<FinanceCategoryDto[]>([]); const [query, setQuery] = useState(""); const [kind, setKind] = useState("ALL"); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [form, setForm] = useState<FormState>(blankForm()); const [editingId, setEditingId] = useState<string | null>(null); const [showForm, setShowForm] = useState(false); const [busy, setBusy] = useState(false);
  const load = async () => { setLoading(true); try { const [transactions, accountItems, categoryItems] = await Promise.all([listFinancialTransactions(), listFinanceAccounts(), listFinanceCategories()]); setRows(transactions); setAccounts(accountItems); setCategories(categoryItems); setForm((current) => current.accountId ? current : blankForm(accountItems.find((item) => item.active && item.group !== "DEBT")?.id ?? accountItems[0]?.id ?? "")); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Không thể tải dữ liệu giao dịch."); } finally { setLoading(false); } };
  useEffect(() => { const timeoutId = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timeoutId); }, []);
  const filtered = useMemo(() => rows.filter((row) => (kind === "ALL" || row.accountType === kind) && `${row.note} ${row.transactionDate} ${row.categoryId}`.toLowerCase().includes(query.toLowerCase())), [query, rows, kind]);
  const setField = <K extends keyof FormState>(key: K, value: FormState[K]) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { const payload = { accountId: form.accountId, transactionDate: form.transactionDate, amount: Number(form.amount), categoryId: form.categoryId, transactionType: form.transactionType, ownership: form.ownership, ...(form.serviceFeeRate !== "" ? { serviceFeeRate: Number(form.serviceFeeRate) } : {}), ...(form.reimbursementExpected !== "" ? { reimbursementExpected: Number(form.reimbursementExpected) } : {}), ...(form.refundReceived !== "" ? { refundReceived: Number(form.refundReceived) } : {}), ...(form.cashbackReceived !== "" ? { cashbackReceived: Number(form.cashbackReceived) } : {}), note: form.note }; if (editingId) await updateFinancialTransaction(editingId, payload as UpdateFinancialTransactionInput); else await createFinancialTransaction(payload); setEditingId(null); setShowForm(false); setForm(blankForm(form.accountId)); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Không thể lưu giao dịch."); } finally { setBusy(false); } };
  const remove = async (row: FinancialTransaction) => { if (!window.confirm(`Xóa giao dịch ${vnd(row.amount)} ngày ${row.transactionDate}?`)) return; setBusy(true); setError(""); try { await deleteFinancialTransaction(row.id); setRows((current) => current.filter((item) => item.id !== row.id)); } catch (e) { setError(e instanceof Error ? e.message : "Không thể xóa giao dịch."); } finally { setBusy(false); } };
  return <FinanceShell title="Giao dịch" action={<button onClick={() => { setEditingId(null); setShowForm(true); }} className="rounded-lg bg-[#087f83] px-4 py-2.5 font-semibold text-white">+ Thêm giao dịch</button>}>
    {showForm ? <section className="cc-section mb-6 p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-bold">{editingId ? "Sửa giao dịch" : "Ghi giao dịch"}</h2><p className="text-sm cc-text-muted">Dữ liệu được ghi vào Financial Domain và cập nhật lại dư nợ/sao kê.</p></div><button type="button" onClick={() => setShowForm(false)} className="cc-control rounded-lg px-3 py-2 text-sm">Đóng</button></div><form onSubmit={submit} className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
      <label className="text-sm font-semibold cc-text-muted">Tài khoản<select required value={form.accountId} onChange={(e) => setField("accountId", e.target.value)} className="cc-control mt-1 w-full rounded-lg px-3 py-2.5">{accounts.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.name} · {item.group}</option>)}</select></label>
      <label className="text-sm font-semibold cc-text-muted">Ngày<input required type="date" value={form.transactionDate} onChange={(e) => setField("transactionDate", e.target.value)} className="cc-control mt-1 w-full rounded-lg px-3 py-2.5" /></label>
      <label className="text-sm font-semibold cc-text-muted">Số tiền<input required min={1} step={1} type="number" value={form.amount} onChange={(e) => setField("amount", e.target.value === "" ? "" : Number(e.target.value))} className="cc-control mt-1 w-full rounded-lg px-3 py-2.5 text-right" /></label>
      <label className="text-sm font-semibold cc-text-muted">Loại<select value={form.transactionType} onChange={(e) => setField("transactionType", e.target.value as FormState["transactionType"])} className="cc-control mt-1 w-full rounded-lg px-3 py-2.5">{editableTypes.map((value) => <option key={value} value={value}>{typeNames[value]}</option>)}</select></label>
      <label className="text-sm font-semibold cc-text-muted">Danh mục<select value={form.categoryId} onChange={(e) => setField("categoryId", e.target.value)} className="cc-control mt-1 w-full rounded-lg px-3 py-2.5"><option value="OTHER">OTHER</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
      <label className="text-sm font-semibold cc-text-muted">Ownership<select value={form.ownership} onChange={(e) => setField("ownership", e.target.value as FormState["ownership"])} className="cc-control mt-1 w-full rounded-lg px-3 py-2.5"><option value="PERSONAL">Cá nhân</option><option value="PAID_FOR_OTHER">Chi hộ</option></select></label>
      <label className="text-sm font-semibold cc-text-muted">Phí dịch vụ %<input min={0} max={100} step="0.01" type="number" value={form.serviceFeeRate} onChange={(e) => setField("serviceFeeRate", e.target.value === "" ? "" : Number(e.target.value))} className="cc-control mt-1 w-full rounded-lg px-3 py-2.5" /></label>
      <label className="text-sm font-semibold cc-text-muted">Phải thu dự kiến<input min={0} step={1} type="number" value={form.reimbursementExpected} onChange={(e) => setField("reimbursementExpected", e.target.value === "" ? "" : Number(e.target.value))} className="cc-control mt-1 w-full rounded-lg px-3 py-2.5" /></label>
      <label className="text-sm font-semibold cc-text-muted md:col-span-2 lg:col-span-3">Ghi chú<input value={form.note} onChange={(e) => setField("note", e.target.value)} className="cc-control mt-1 w-full rounded-lg px-3 py-2.5" /></label>
      <div className="flex items-end gap-2"><button disabled={busy || !form.accountId} className="rounded-lg bg-[#087f83] px-4 py-2.5 font-bold text-white disabled:opacity-60">{busy ? "Đang lưu..." : editingId ? "Cập nhật" : "Ghi giao dịch"}</button><button type="button" onClick={() => setShowForm(false)} className="cc-control rounded-lg px-4 py-2.5">Hủy</button></div>
    </form></section> : null}
    <section className="cc-section overflow-hidden p-5"><div className="mb-5 flex flex-col gap-3 lg:flex-row"><input aria-label="Tìm giao dịch" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Tìm theo ghi chú, danh mục hoặc ngày..." className="cc-control flex-1 rounded-lg px-3 py-2.5" /><div className="flex gap-2 overflow-x-auto">{["ALL", "DEBIT", "CASH", "E_WALLET", "CREDIT"].map((value) => <button key={value} onClick={() => setKind(value)} className={`rounded-lg px-3 py-2 text-sm font-semibold ${kind === value ? "bg-slate-900 text-white" : "bg-slate-100"}`}>{value === "ALL" ? "Tất cả" : typeLabel[value]}</button>)}</div></div>{loading ? <p className="py-12 text-center cc-text-muted">Đang tải giao dịch...</p> : error ? <p role="alert" className="rounded-lg bg-red-50 p-4 text-red-700">{error}</p> : filtered.length === 0 ? <p className="py-12 text-center cc-text-muted">Chưa có giao dịch phù hợp.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[1080px] text-sm"><thead><tr className="border-b"><th className="p-3 text-left">Ngày</th><th className="p-3 text-left">Phương thức</th><th className="p-3 text-left">Danh mục</th><th className="p-3 text-left">Ownership</th><th className="p-3 text-right">Số tiền</th><th className="p-3 text-right">Cá nhân</th><th className="p-3 text-right">Phải thu</th><th className="p-3 text-right">Nợ credit</th><th className="p-3"></th></tr></thead><tbody>{filtered.map((row) => <tr key={row.id} className="border-b"><td className="p-3 font-mono">{row.transactionDate}</td><td className="p-3"><span className={`rounded px-2 py-1 text-xs font-bold ${typeClass[row.accountType]}`}>{typeLabel[row.accountType]} · {typeNames[row.transactionType] ?? row.transactionType}</span></td><td className="p-3">{row.categoryId}<p className="text-xs cc-text-muted">{row.note}</p></td><td className="p-3">{row.ownership === "PAID_FOR_OTHER" ? "Chi hộ" : "Cá nhân"}</td><td className="p-3 text-right font-semibold">{vnd(row.amount)}</td><td className="p-3 text-right">{vnd(row.impact.personalSpending)}</td><td className="p-3 text-right text-orange-600">{vnd(row.impact.outstandingReceivable)}</td><td className="p-3 text-right text-violet-700">{vnd(row.impact.creditDebt)}</td><td className="p-3 text-right"><button type="button" onClick={() => { setForm(toForm(row)); setEditingId(row.id); setShowForm(true); }} className="mr-3 text-xs font-bold text-cyan-700">Sửa</button><button type="button" disabled={busy} onClick={() => void remove(row)} className="text-xs font-bold text-red-600">Xóa</button></td></tr>)}</tbody></table></div>}</section>
  </FinanceShell>;
}
