"use client";

import { FormEvent, useEffect, useState } from "react";
import { createCalendarSubscription, listCalendarSubscriptions, revokeCalendarSubscription, type CalendarSubscription } from "@/lib/api/calendarSubscriptionsClient";

export function CalendarSubscriptionSettings() {
  const [items, setItems] = useState<CalendarSubscription[]>([]); const [label, setLabel] = useState(""); const [revealedUrl, setRevealedUrl] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { let active = true; void listCalendarSubscriptions().then((data) => { if (active) setItems(data); }).catch((e) => { if (active) setError(e instanceof Error ? e.message : "Không thể tải lịch đăng ký."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const create = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(""); setMessage(""); setRevealedUrl(""); try { const created = await createCalendarSubscription(label); setItems((current) => [created, ...current]); setRevealedUrl(new URL(created.subscriptionPath, window.location.origin).toString()); setLabel(""); setMessage("Đã tạo URL. Hãy lưu ngay vì URL đầy đủ sẽ không được hiển thị lại."); } catch (e) { setError(e instanceof Error ? e.message : "Không thể tạo lịch đăng ký."); } finally { setBusy(false); } };
  const revoke = async (item: CalendarSubscription) => { if (!window.confirm(`Thu hồi lịch ${item.deviceLabel || "không có nhãn"}? Thiết bị sẽ không thể cập nhật lịch nữa.`)) return; setBusy(true); setError(""); try { await revokeCalendarSubscription(item.id); setItems((current) => current.map((value) => value.id === item.id ? { ...value, revokedAt: new Date().toISOString() } : value)); setRevealedUrl(""); setMessage("Đã thu hồi lịch đăng ký."); } catch (e) { setError(e instanceof Error ? e.message : "Không thể thu hồi lịch đăng ký."); } finally { setBusy(false); } };
  const copy = async () => { try { await navigator.clipboard.writeText(revealedUrl); setMessage("Đã sao chép URL lịch."); } catch { setError("Không thể sao chép tự động. Hãy chọn và sao chép URL thủ công."); } };
  return <section aria-labelledby="calendar-subscription-title" className="mt-6 rounded-lg border border-gray-200 bg-white p-6 shadow-sm">
    <h2 id="calendar-subscription-title" className="text-xl font-bold">Lịch hạn thanh toán</h2>
    <p className="mt-2 text-sm text-gray-600">Tạo URL riêng tư để đăng ký một lần trên Apple Calendar. URL cho phép đọc các hạn thanh toán hiện tại của bạn; hãy bảo vệ URL như mật khẩu.</p>
    <form onSubmit={create} className="mt-4 flex flex-col gap-3 sm:flex-row"><label className="min-w-0 flex-1 text-sm font-semibold">Nhãn thiết bị (không bắt buộc)<input value={label} onChange={(e) => setLabel(e.target.value)} maxLength={80} placeholder="iPhone cá nhân" className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 font-normal outline-none focus:ring-2 focus:ring-emerald-500" /></label><button disabled={busy} className="self-end rounded-lg bg-emerald-600 px-5 py-2 font-semibold text-white disabled:opacity-60">{busy ? "Đang xử lý..." : "Tạo URL lịch"}</button></form>
    {revealedUrl ? <div className="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-4"><p className="text-sm font-semibold text-amber-900">URL chỉ hiển thị đầy đủ lần này</p><input aria-label="URL lịch đăng ký" readOnly value={revealedUrl} onFocus={(e) => e.currentTarget.select()} className="mt-2 w-full rounded border border-amber-300 bg-white px-3 py-2 text-sm" /><div className="mt-2 flex flex-wrap gap-2"><button type="button" onClick={() => void copy()} className="rounded bg-gray-900 px-3 py-2 text-sm font-semibold text-white">Sao chép</button><a href={revealedUrl} className="rounded border border-gray-400 bg-white px-3 py-2 text-sm font-semibold">Mở URL</a></div></div> : null}
    {message ? <p role="status" className="mt-3 text-sm font-medium text-emerald-700">{message}</p> : null}{error ? <p role="alert" className="mt-3 text-sm font-medium text-red-700">{error}</p> : null}
    <div className="mt-5 border-t border-gray-100 pt-4"><h3 className="font-semibold">Các lịch đã tạo</h3>{loading ? <p role="status" className="mt-2 text-sm text-gray-500">Đang tải...</p> : items.length === 0 ? <p className="mt-2 text-sm text-gray-500">Chưa có lịch đăng ký.</p> : <ul className="mt-2 space-y-2">{items.map((item) => <li key={item.id} className="flex flex-col gap-2 rounded-lg border border-gray-200 p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{item.deviceLabel || "Không có nhãn"}</p><p className="text-xs text-gray-500">Tạo: {new Date(item.createdAt).toLocaleString("vi-VN")} · {item.revokedAt ? "Đã thu hồi" : item.lastAccessedAt ? `Cập nhật gần nhất: ${new Date(item.lastAccessedAt).toLocaleString("vi-VN")}` : "Chưa được truy cập"}</p></div>{!item.revokedAt ? <button type="button" disabled={busy} onClick={() => void revoke(item)} className="self-start rounded border border-red-300 px-3 py-1.5 text-sm font-semibold text-red-700 disabled:opacity-60">Thu hồi</button> : null}</li>)}</ul>}</div>
  </section>;
}
